---
- name: Converge
  hosts: all
  gather_facts: false

  pre_tasks:
    - name: PRE_TASK | Install python3
      changed_when: false
      ansible.builtin.raw: |
        id_like=$(grep -Ewo "debian|fedora" /etc/os-release | uniq)
        case "${id_like}" in
          debian)
            apt update
            apt -y install python3
          ;;
          fedora)
            dnf makecache
            dnf -y install python3
          ;;
        esac
    - name: Gather facts
      ansible.builtin.setup:

  roles:
    - role: xenion1987.sshd
      vars:
        sshd_config_lines:
          - Port 22222
          - permit_root_login no
          - password_authentication no
          - permit_empty_passwords no
